---

- name: create dotnetdev.list file
  file: path=/etc/apt/sources.list.d/dotnetdev.list state=touch owner=root group=root mode=0755
- name: set apt-get feed Ubuntu Xenial
  lineinfile: dest=/etc/apt/sources.list.d/dotnetdev.list line="deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ xenial main"
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16" 
- name: set apt-get feed Ubuntu Trusty
  lineinfile: dest=/etc/apt/sources.list.d/dotnetdev.list line="deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main"
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14"
- name: apt key add
  apt_key: keyserver=apt-mo.trafficmanager.net id=417A0893
- name: Updating apt cache
  apt:
    update_cache: yes

- name: install .NET Core
  apt:
    name: dotnet-dev-1.0.1
    state: present
- name: Copy payload and untar
  unarchive: src=../artifacts/dotNetCore.tar dest=/home/vagrant
- name: dotnet routine
  command: chdir=/home/vagrant/dotNetCore dotnet {{ item }}
  with_items:
    - migrate
    - restore

- name: hack for Zabbix
  apt: name={{item}} state=present
  with_items:
    - php7.0-bcmath 
    - php7.0-mbstring 
    - php7.0-xml

- name: install Redis Server
  apt:
    name: redis-server
    state: present
- name: Ensure Redis is started
  service: name=redis-server state=started enabled=yes
- name: Ensure Redis Configuration
  template: src=../artifacts/redis.conf.j2 dest=/etc/redis/redis.conf owner=root group=root mode=0644
  notify: Redis Restart
